define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var Bullet, Movable,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Movable = require('../movable');

Bullet = (function(_super) {
  var HIDDEN_Z;

  __extends(Bullet, _super);

  Bullet.name = 'Bullet';

  HIDDEN_Z = 2000;

  Bullet.prototype.solid = false;

  Bullet.prototype.mass = 0;

  function Bullet(options) {
    Bullet.__super__.constructor.call(this, options);
  }

  Bullet.prototype.setup = function(parent) {
    this.parent = parent;
    this.position.set(this.parent.position.x, this.parent.position.y, this.parent.position.z - 10);
    this.rotation = this.parent.rotation - (Math.PI * 1.5);
    this.mesh.rotateAboutObjectAxis(THREE.AxisZ, this.rotation);
    this.velocity.x = Math.cos(this.parent.rotation);
    this.velocity.y = Math.sin(this.parent.rotation);
    return this.alive = true;
  };

  Bullet.prototype.remove = function() {
    this.alive = false;
    this.position.z = HIDDEN_Z;
    return this.mesh.rotateAboutObjectAxis(THREE.AxisZ, -this.rotation);
  };

  Bullet.prototype.step = function() {
    if (this.alive) {
      if (this.lifetime > 0) {
        this.position.addSelf(this.velocity);
        return this.lifetime--;
      } else {
        return this.remove();
      }
    }
  };

  Bullet.prototype.handleCollision = function(other) {
    if (!other.solid) {
      return;
    }
    if (other === this.parent) {
      return;
    }
    other.health -= this.damage;
    if (other.health <= 0) {
      other.explode();
    }
    return this.remove();
  };

  return Bullet;

})(Movable);

module.exports = Bullet;

});
