define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var Trail, TurretBulletTrail,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Trail = require('./trail');

TurretBulletTrail = (function(_super) {

  __extends(TurretBulletTrail, _super);

  TurretBulletTrail.name = 'TurretBulletTrail';

  function TurretBulletTrail() {
    return TurretBulletTrail.__super__.constructor.apply(this, arguments);
  }

  TurretBulletTrail.prototype.max_lifetime = 5;

  TurretBulletTrail.prototype.max_opacity = 0.5;

  TurretBulletTrail.prototype.min_opacity = 0;

  TurretBulletTrail.prototype.setup = function(position) {
    TurretBulletTrail.__super__.setup.apply(this, arguments);
    this.velocity.set((Math.random() - 0.5) / 2, (Math.random() - 0.5) / 2, 0);
    return this.mesh.material.color.setRGB(100, 100, 100);
  };

  TurretBulletTrail.prototype.remove = function() {
    TurretBulletTrail.__super__.remove.apply(this, arguments);
    return this.universe.trails.addToTurretBulletTrailPool(this);
  };

  return TurretBulletTrail;

})(Trail);

module.exports = TurretBulletTrail;

});
