define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1

$(document).ready(function() {
  var Engine;
  if (!Detector.webgl) {
    Detector.addGetWebGLMessage();
    return;
  }
  Engine = require('engine');
  return new Engine({
    container: document.getElementById('container'),
    aiPlayers: 1
  });
});

});
