define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var BulletsStorage, ShipBullet, TurretBullet;

ShipBullet = require('ship_bullet');

TurretBullet = require('turret_bullet');

BulletsStorage = (function() {

  BulletsStorage.name = 'BulletsStorage';

  function BulletsStorage(options) {
    this.universe = options.universe;
    this.controller = options.controller;
    this.shipBulletPool = [];
    this.turretBulletPool = [];
  }

  BulletsStorage.prototype.addToShipBulletPool = function(bullet) {
    return this.shipBulletPool.push(bullet);
  };

  BulletsStorage.prototype.addToTurretBulletPool = function(bullet) {
    return this.turretBulletPool.push(bullet);
  };

  BulletsStorage.prototype.newShipBullet = function(parent) {
    var bullet;
    bullet = this.shipBulletPool.pop();
    if (!bullet) {
      bullet = new ShipBullet({
        controller: this.controller,
        universe: this.universe
      });
    }
    return bullet.setup(parent);
  };

  BulletsStorage.prototype.newTurretBullet = function(parent) {
    var bullet;
    bullet = this.turretBulletPool.pop();
    if (!bullet) {
      bullet = new TurretBullet({
        controller: this.controller,
        universe: this.universe
      });
    }
    return bullet.setup(parent);
  };

  return BulletsStorage;

})();

module.exports = BulletsStorage;

});
