define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var MainMenu, Menu, TurretMenu,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

require('templates');

Menu = (function(_super) {

  __extends(Menu, _super);

  Menu.name = 'Menu';

  function Menu() {
    return Menu.__super__.constructor.apply(this, arguments);
  }

  Menu.prototype.className = 'menu';

  Menu.prototype.width = 600;

  Menu.prototype.height = 600;

  Menu.prototype.left = function() {
    return this;
  };

  Menu.prototype.right = function() {
    return this;
  };

  Menu.prototype.up = function() {
    return this;
  };

  Menu.prototype.down = function() {
    return this;
  };

  Menu.prototype.render = function() {
    this.$el.append(this.template);
    this.$el.css('width', this.width);
    this.$el.css('height', this.height);
    this.$el.css('left', (window.innerWidth - this.width) / 2);
    this.$el.css('top', (window.innerHeight - this.height) / 2);
    return this;
  };

  Menu.prototype.dispose = function() {
    this.$el.remove();
    return false;
  };

  Menu.prototype.switchMenu = function(menuClass) {
    var menu;
    menu = new menuClass;
    this.$el.replaceWith(menu.render().el);
    return menu;
  };

  return Menu;

})(Backbone.View);

MainMenu = (function(_super) {

  __extends(MainMenu, _super);

  MainMenu.name = 'MainMenu';

  function MainMenu() {
    return MainMenu.__super__.constructor.apply(this, arguments);
  }

  MainMenu.prototype.template = JST['game_menu/main_menu'];

  MainMenu.prototype.left = function() {
    return this.switchMenu(TurretMenu);
  };

  return MainMenu;

})(Menu);

TurretMenu = (function(_super) {

  __extends(TurretMenu, _super);

  TurretMenu.name = 'TurretMenu';

  function TurretMenu() {
    return TurretMenu.__super__.constructor.apply(this, arguments);
  }

  TurretMenu.prototype.template = JST['game_menu/turret_menu'];

  TurretMenu.prototype.left = function(engine) {
    engine.universe.player.buildTurret();
    return this.dispose();
  };

  TurretMenu.prototype.right = function(engine) {
    engine.universe.player.buildMassDriver();
    return this.dispose();
  };

  return TurretMenu;

})(Menu);

module.exports = MainMenu;

});
