define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var Bullet, ShipBullet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Bullet = require('bullet');

ShipBullet = (function(_super) {

  __extends(ShipBullet, _super);

  ShipBullet.name = 'ShipBullet';

  function ShipBullet() {
    return ShipBullet.__super__.constructor.apply(this, arguments);
  }

  ShipBullet.prototype.damage = 100;

  ShipBullet.prototype.radius = 5;

  ShipBullet.prototype.buildMesh = function() {
    var geometry, material;
    geometry = new THREE.SphereGeometry(5);
    material = new THREE.MeshBasicMaterial;
    return new THREE.Mesh(geometry, material);
  };

  ShipBullet.prototype.setup = function(parent) {
    this.parent = parent;
    ShipBullet.__super__.setup.apply(this, arguments);
    this.velocity.multiplyScalar(6);
    this.mesh.material.color.setRGB(89 / 255, 163 / 255, 89 / 255);
    return this.lifetime = 100;
  };

  ShipBullet.prototype.remove = function() {
    ShipBullet.__super__.remove.apply(this, arguments);
    return this.universe.bullets.addToShipBulletPool(this);
  };

  return ShipBullet;

})(Bullet);

module.exports = ShipBullet;

});
