define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var Bullet, TurretBullet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Bullet = require('bullet');

TurretBullet = (function(_super) {

  __extends(TurretBullet, _super);

  TurretBullet.name = 'TurretBullet';

  function TurretBullet() {
    return TurretBullet.__super__.constructor.apply(this, arguments);
  }

  TurretBullet.prototype.damage = 100;

  TurretBullet.prototype.radius = 5;

  TurretBullet.prototype.buildMesh = function() {
    var geometry, material;
    geometry = new THREE.CylinderGeometry(2, 1, 10, 10);
    material = new THREE.MeshBasicMaterial;
    return new THREE.Mesh(geometry, material);
  };

  TurretBullet.prototype.setup = function(parent) {
    this.parent = parent;
    TurretBullet.__super__.setup.apply(this, arguments);
    this.velocity.multiplyScalar(6);
    this.mesh.material.color.setRGB(89 / 255, 163 / 255, 89 / 255);
    return this.lifetime = 100;
  };

  TurretBullet.prototype.remove = function() {
    TurretBullet.__super__.remove.apply(this, arguments);
    return this.universe.bullets.addToTurretBulletPool(this);
  };

  TurretBullet.prototype.step = function() {
    TurretBullet.__super__.step.apply(this, arguments);
    if (this.alive) {
      return this.universe.trails.newTurretBulletTrail(this);
    }
  };

  return TurretBullet;

})(Bullet);

module.exports = TurretBullet;

});
