define(function(require, exports, module){
// Generated by CoffeeScript 1.3.1
var ShipTrail, TrailsStorage, TurretBulletTrail;

ShipTrail = require('trails/ship_trail');

TurretBulletTrail = require('trails/turret_bullet_trail');

TrailsStorage = (function() {

  TrailsStorage.name = 'TrailsStorage';

  function TrailsStorage(options) {
    this.universe = options.universe;
    this.controller = options.controller;
    this.shipTrailPool = [];
    this.turretBulletTrailPool = [];
  }

  TrailsStorage.prototype.addToShipTrailPool = function(trail) {
    return this.shipTrailPool.push(trail);
  };

  TrailsStorage.prototype.addToTurretBulletTrailPool = function(trail) {
    return this.turretBulletTrailPool.push(trail);
  };

  TrailsStorage.prototype.newShipTrail = function(parent) {
    var i, trail, _i, _results;
    _results = [];
    for (i = _i = 1; _i <= 2; i = ++_i) {
      trail = this.shipTrailPool.pop();
      if (!trail) {
        trail = new ShipTrail({
          controller: this.controller,
          universe: this.universe
        });
      }
      _results.push(trail.setup(parent.position));
    }
    return _results;
  };

  TrailsStorage.prototype.newTurretBulletTrail = function(parent) {
    var trail;
    trail = this.turretBulletTrailPool.pop();
    if (!trail) {
      trail = new TurretBulletTrail({
        controller: this.controller,
        universe: this.universe
      });
    }
    return trail.setup(parent.position);
  };

  return TrailsStorage;

})();

module.exports = TrailsStorage;

});
